security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        users_in_memory: 
            memory:
                users:
                    test:
                        password: $2y$13$cjDKYLOP8CvpJ0wmHbe63.vX6UgvN7E2Kes7VNx9x20OmyuatI01m
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            http_basic:
                provider: users_in_memory
        main:
            lazy: true
            provider: users_in_memory
    access_control:
        - { path: '^/api/form', roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/api/upload-file', roles: IS_AUTHENTICATED_FULLY }
