render_form:
    path: /api/form
    controller: App\SiteRenderer\Controller\FormRendererAction
    methods: [GET]

render_table:
    path: /api/table
    controller: App\SiteRenderer\Controller\TableRendererAction
    methods: [GET]
    
upload_file:
    path: /api/upload-file
    controller: App\File\Controller\UploadAction
    methods: [POST]

